### ISSUE TITLE
generate statement has error. nullpoingexception

### ISSUE THREAD

**Issue by wenzhihong2003** [seventh7/intellij-mybatis-plugin#37]
hi, when a Mapper class map to 2 xml file. for example:
```java
package com.yijushang.yivshop.business.repository;
@Repository
public interface BrokerageFetchMapper {
    List<BrokerageFetch> selectById(@Param("id") Long id);
}
```
and 2 xml file use the same namespace:
1.xml
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<mapper namespace="com.yijushang.yivshop.business.repository.BrokerageFetchMapper">
</mapper>
```
-------------------------------------------
2.xml
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<mapper namespace="com.yijushang.yivshop.business.repository.BrokerageFetchMapper">
</mapper>
```
---------------------------------------------
when caret on mapper class, use shortcut alt + enter, can show pop tip which xml file to place generate, then select one item, it report a error. 
the error statck is:
```java
null
java.lang.NullPointerException
	at com.intellij.psi.impl.source.tree.ChangeUtil.a(ChangeUtil.java:87)
	at com.intellij.psi.impl.source.tree.ChangeUtil.decodeInformation(ChangeUtil.java:79)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.addAfter(CompositePsiElement.java:162)
	at com.intellij.util.xml.impl.DomInvocationHandler.a(DomInvocationHandler.java:828)
	at com.intellij.util.xml.impl.DomInvocationHandler.addCollectionChild(DomInvocationHandler.java:795)
	at com.intellij.util.xml.impl.AddChildInvocation.invoke(AddChildInvocation.java:43)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:689)
	at com.seventh7.mybatis.dom.model.Mapper$$EnhancerByCGLIB$$a948bc64.addSelect(<generated>)
	at com.seventh7.mybatis.generate.SelectGenerator.getComparableTarget(SelectGenerator.java:24)
	at com.seventh7.mybatis.generate.StatementGenerator.setupTag(StatementGenerator.java:158)
	at com.seventh7.mybatis.generate.StatementGenerator.access$100(StatementGenerator.java:40)
	at com.seventh7.mybatis.generate.StatementGenerator$4.selected(StatementGenerator.java:146)
	at com.seventh7.mybatis.ui.UiComponentFacade$3.run(UiComponentFacade.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at com.seventh7.mybatis.ui.UiComponentFacade.setActionForExecutableListener(UiComponentFacade.java:120)
	at com.seventh7.mybatis.ui.UiComponentFacade.access$000(UiComponentFacade.java:34)
	at com.seventh7.mybatis.ui.UiComponentFacade$4.run(UiComponentFacade.java:143)
	at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1343)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:651)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:632)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:602)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:498)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2108)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:476)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:990)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$300(ActionToolbarImpl.java:64)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$MyTimerListener.run(ActionToolbarImpl.java:893)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:50)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1498)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1488)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1472)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by seventh7** [comment]
Hi, sorry for delayed reply. Mapper xml with the same namespace is not supported
