### ISSUE TITLE
IntelliJ 14.1 EAP error

### ISSUE THREAD

**Issue by librucha** [seventh7/intellij-mybatis-plugin#38]
org/jetbrains/generate/tostring/util/StringUtil
java.lang.NoClassDefFoundError: org/jetbrains/generate/tostring/util/StringUtil
	at com.seventh7.mybatis.util.MapperUtils.findDuplicateElements(MapperUtils.java:226)
	at com.seventh7.mybatis.inspection.MapperXmlInspection.checkDomElement(MapperXmlInspection.java:34)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:71)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFileElement(DomElementsInspection.java:74)
	at com.intellij.util.xml.highlighting.DomElementAnnotationsManagerImpl.checkFileElement(DomElementAnnotationsManagerImpl.java:256)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkDomFile(DomElementsInspection.java:150)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFile(DomElementsInspection.java:123)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:151)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:74)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:289)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:258)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:255)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1107)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:282)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:279)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.generate.tostring.util.StringUtil PluginClassLoader[com.seventh7.plugin.mybatis, 2.32]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 32 more

**Comment by natros** [comment]
same problem here with 140.2285.5

**Comment by natros** [comment]
and with 14.1 RC2

**Comment by peterlitvak** [comment]
This issue made in to the 14.1 release :( would be nice to address it at this point

**Comment by soulLink** [comment]
same problem here  14.1   please help ME

**Comment by seventh7** [comment]
The problem was fixed and it will release later. Thank you guys for feedback
