### ISSUE TITLE
插件在141.177版本上运行报错

### ISSUE THREAD

**Issue by rockjava** [seventh7/intellij-mybatis-plugin#42]
在mapper.xml中跳转到mapper类的过程报错
org/jetbrains/generate/tostring/util/StringUtil
java.lang.NoClassDefFoundError: org/jetbrains/generate/tostring/util/StringUtil
	at com.seventh7.mybatis.util.MapperUtils.findDuplicateElements(MapperUtils.java:226)
	at com.seventh7.mybatis.inspection.MapperXmlInspection.checkDomElement(MapperXmlInspection.java:34)

**Comment by DowenLiu126** [comment]
Mapper接口跳转到mapper.xml的时候报的错，异常栈和楼上一致

**Comment by youpengfei** [comment]
对的，目前本人的也出现这个问题下午5:31:38 NoClassDefFoundError: org/jetbrains/generate/tostring/util/StringUtil

**Comment by seventh7** [comment]
感谢反馈，下个版本Fix
